import type { EcosystemEntity } from "./types";

/**
 * A deliberately reviewed seed registry. Popularity is only fetched for
 * entities with an explicit public identifier; it is never inferred from a
 * name search, which would attach a popular repository to the wrong product.
 */
export const ECOSYSTEM_ENTITIES: EcosystemEntity[] = [
  { id: "langchain", name: "LangChain", type: "framework", description: "Framework for building applications with language models.", websiteUrl: "https://www.langchain.com", repositoryUrl: "https://github.com/langchain-ai/langchain", npmPackage: "langchain", audiences: ["developer", "business"], useCases: ["agents", "rag", "orchestration"] },
  { id: "langgraph", name: "LangGraph", type: "framework", description: "Graph-based orchestration for stateful agents.", websiteUrl: "https://langchain-ai.github.io/langgraphjs", repositoryUrl: "https://github.com/langchain-ai/langgraphjs", npmPackage: "@langchain/langgraph", audiences: ["developer", "business"], useCases: ["agents", "orchestration"] },
  { id: "llamaindex", name: "LlamaIndex", type: "framework", description: "Data and retrieval framework for LLM applications.", websiteUrl: "https://www.llamaindex.ai", repositoryUrl: "https://github.com/run-llama/llama_index", npmPackage: "llamaindex", audiences: ["developer", "researcher"], useCases: ["rag", "agents", "data"] },
  { id: "crewai", name: "CrewAI", type: "framework", description: "Framework for orchestrating collaborative agents.", websiteUrl: "https://www.crewai.com", repositoryUrl: "https://github.com/crewAIInc/crewAI", audiences: ["developer", "business"], useCases: ["agents", "automation"] },
  { id: "autogen", name: "AutoGen", type: "framework", description: "Framework for multi-agent applications.", websiteUrl: "https://microsoft.github.io/autogen", repositoryUrl: "https://github.com/microsoft/autogen", audiences: ["developer", "researcher"], useCases: ["agents", "research"] },
  { id: "semantic-kernel", name: "Semantic Kernel", type: "framework", description: "Microsoft SDK for integrating AI models into applications.", websiteUrl: "https://learn.microsoft.com/semantic-kernel", repositoryUrl: "https://github.com/microsoft/semantic-kernel", audiences: ["developer", "business"], useCases: ["agents", "enterprise"] },
  { id: "dspy", name: "DSPy", type: "framework", description: "Programming framework for declarative language-model systems.", websiteUrl: "https://dspy.ai", repositoryUrl: "https://github.com/stanfordnlp/dspy", audiences: ["developer", "researcher"], useCases: ["optimization", "research"] },
  { id: "haystack", name: "Haystack", type: "framework", description: "Open-source framework for production search and RAG systems.", websiteUrl: "https://haystack.deepset.ai", repositoryUrl: "https://github.com/deepset-ai/haystack", audiences: ["developer", "business"], useCases: ["rag", "search"] },
  { id: "vercel-ai-sdk", name: "Vercel AI SDK", type: "framework", description: "TypeScript toolkit for building AI-powered applications.", websiteUrl: "https://ai-sdk.dev", repositoryUrl: "https://github.com/vercel/ai", npmPackage: "ai", audiences: ["developer", "business"], useCases: ["applications", "agents", "streaming"] },
  { id: "mastra", name: "Mastra", type: "framework", description: "TypeScript framework for AI agents and workflows.", websiteUrl: "https://mastra.ai", repositoryUrl: "https://github.com/mastra-ai/mastra", npmPackage: "@mastra/core", audiences: ["developer", "business"], useCases: ["agents", "workflows"] },
  { id: "ollama", name: "Ollama", type: "infrastructure", description: "Local runtime for running open models.", websiteUrl: "https://ollama.com", repositoryUrl: "https://github.com/ollama/ollama", audiences: ["developer", "general-user", "researcher"], useCases: ["local-ai", "self-hosting"] },
  { id: "vllm", name: "vLLM", type: "infrastructure", description: "High-throughput serving engine for language models.", websiteUrl: "https://vllm.ai", repositoryUrl: "https://github.com/vllm-project/vllm", audiences: ["developer", "business", "researcher"], useCases: ["serving", "self-hosting"] },
  { id: "litellm", name: "LiteLLM", type: "infrastructure", description: "Unified interface and gateway for language-model providers.", websiteUrl: "https://litellm.ai", repositoryUrl: "https://github.com/BerriAI/litellm", audiences: ["developer", "business"], useCases: ["gateway", "observability"] },
  { id: "open-webui", name: "Open WebUI", type: "application", description: "Self-hosted web interface for AI models.", websiteUrl: "https://openwebui.com", repositoryUrl: "https://github.com/open-webui/open-webui", audiences: ["general-user", "developer", "business"], useCases: ["chat", "local-ai"] },
  { id: "librechat", name: "LibreChat", type: "application", description: "Multi-provider conversational AI application.", websiteUrl: "https://www.librechat.ai", repositoryUrl: "https://github.com/danny-avila/LibreChat", audiences: ["general-user", "developer", "business"], useCases: ["chat", "applications"] },
  { id: "continue", name: "Continue", type: "application", description: "Open-source AI code assistant for developer environments.", websiteUrl: "https://www.continue.dev", repositoryUrl: "https://github.com/continuedev/continue", audiences: ["developer"], useCases: ["coding", "agents"] },
  { id: "aider", name: "Aider", type: "agent", description: "Terminal pair-programming agent for codebases.", websiteUrl: "https://aider.chat", repositoryUrl: "https://github.com/Aider-AI/aider", audiences: ["developer"], useCases: ["coding", "agents"] },
  { id: "openhands", name: "OpenHands", type: "agent", description: "Open-source platform for software-development agents.", websiteUrl: "https://openhands.dev", repositoryUrl: "https://github.com/All-Hands-AI/OpenHands", audiences: ["developer", "researcher"], useCases: ["coding", "agents"] },
  { id: "browser-use", name: "browser-use", type: "agent", description: "Library for enabling agents to control browsers.", websiteUrl: "https://browser-use.com", repositoryUrl: "https://github.com/browser-use/browser-use", audiences: ["developer", "researcher"], useCases: ["browsing", "agents", "automation"] },
  { id: "model-context-protocol", name: "Model Context Protocol", type: "tool", description: "Open protocol for connecting models to tools and data.", websiteUrl: "https://modelcontextprotocol.io", repositoryUrl: "https://github.com/modelcontextprotocol", audiences: ["developer", "business"], useCases: ["tools", "integrations", "agents"] },
];
